# Generated by Django 3.0.8 on 2020-09-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_readnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='readed_num',
            new_name='read_num',
        ),
    ]
